apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s  # Adjust for faster data collection
    scrape_configs:
      - job_name: 'url-shortener'
        static_configs:
          - targets: ['url-shortener.default.svc.cluster.local:8080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.default.svc.cluster.local:9100']

